fast:
	bibtex   perturb-colt.aux
	pdflatex perturb-colt.tex
	evince   perturb-colt.pdf

full:
	pdflatex perturb-colt.tex
	bibtex   perturb-colt.aux
	pdflatex perturb-colt.tex
	pdflatex perturb-colt.tex
	evince   perturb-colt.pdf
