fast:
	bibtex   perturb-aaai.aux
	pdflatex perturb-aaai.tex
	evince   perturb-aaai.pdf

full:
	pdflatex perturb-aaai.tex
	bibtex   perturb-aaai.aux
	pdflatex perturb-aaai.tex
	pdflatex perturb-aaai.tex
	evince   perturb-aaai.pdf

