slides:
	pdflatex slides.tex
	bibtex   slides.aux
	evince 	 slides.pdf

fast:
	pdflatex thesis.tex
	evince   thesis.pdf

thesis:
	pdflatex thesis.tex
	bibtex   thesis.aux
	pdflatex thesis.tex
	pdflatex thesis.tex
